### ISSUE TITLE
All shard names must be integers

### ISSUE THREAD

**Issue by rossi-jeff** [zendesk/active_record_shards#195]
my first reaction was 'what??'

trying to evaluate your gem as a replacement for octopus which does not work with rails 5.2 

is it possible to use named shards without forking the gem?

**Comment by vaibhavpaliwal** [comment]
Yes, its possible.. in my project we use guids something like below:

```
  shards:
    asdd13-c755-478d-b343-sdf900203:
      database: test
    asddw-123451-484e-b0d3-uahf2738:
      database: abc
```
