### ISSUE TITLE
"where" doesn't work when on_shard (Rails 3.2)

### ISSUE THREAD

**Issue by lukkry** [zendesk/active_record_shards#6]
ActiveRecordShards tries to read from not sharded database when calling

``` ruby
ActiveRecord::Base.on_shard(1){ Project.where(:id => 1) }
```

Steps to reproduce:
- create a new rails 3.2.14 app
- add active_record_shards to Gemfile
- create database.yml

``` yaml
development:
  adapter: mysql2
  encoding: utf8
  database: mango
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  slave:
    database: mango_slave
  shards:
    1:
      database: mango_shard0
      slave:
        database: mango_shard0_slave
    2:
      database: mango_shard1
      slave:
        database: mango_shard1_slave
```
- `$ bundle exec rails g model Project name:string`

``` ruby
class CreateProjects < ActiveRecord::Migration
  shard :all

  def change
    create_table :projects do |t|
      t.string :name

      t.timestamps
    end
  end
end
```
- `$ bundle exec rake db:migrate`
- `$ bundle exec rails c`

``` shell
1.9.3-p429 :008 > ActiveRecord::Base.on_shard(1){ Project.connection.current_database }
   (2.5ms)  SELECT DATABASE() as db
 => "mango_shard0"
1.9.3-p429 :006 > ActiveRecord::Base.on_shard(1){ Project.all }
  Project Load (0.3ms)  SELECT `projects`.* FROM `projects`
 => []
1.9.3-p429 :001 > ActiveRecord::Base.on_shard(1){ Project.where(:id => 1) }
  Project Load (0.3ms)  SELECT `projects`.* FROM `projects` WHERE `projects`.`id` = 1
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'mango.projects' doesn't exist: SELECT `projects`.* FROM `projects`  WHERE `projects`.`id` = 1
```

Am I missing something obvious here?
